abacus_dataset: wideprior_AB
accelerator: gpu
accumulate_grad_batches: null
act_fn: SiLU
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 256
benchmark: null
check_val_every_n_epoch: 1
default_root_dir: null
detect_anomaly: false
devices: null
dropout_rate: 0.06564060158847812
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
inference_mode: true
input_names: null
ipus: null
learning_rate: 0.03268045249251676
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
loss: gaussian
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_dir: ../../trained_models
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_hidden:
- 583
- 408
n_input: 17
n_output: 72
normalize_covariance: true
normalize_inputs: true
normalize_outputs: true
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
run_name: optuna_cross_4
select_multipoles:
- 0
- 1
select_quintiles:
- 4
slice_s:
- 0.7
- 150.0
standarize_outputs: false
statistic: density_split_cross
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
train_test_split_path: ../../data/train_test_split.json
val_check_interval: null
weight_decay: 0.0073116485205852455
