slice_filters:
    s: [0.7,120.]

select_filters:
    multipoles: [0,2]

statistics: ['voids']
data:
    observation: 
        class: 'Abacus'
    args:
        dataset: 'voidprior'
    get_obs_args:
        cosmology: 0
        hod_idx: 26
    covariance:
        class: 'Patchy'
        add_emulator_error: true
        add_simulation_error: false
        volume_scaling: 1.0

fixed_parameters: ['nrun','N_ur','w0_fld','wa_fld'] 

theory_model:
    module: 'sunbird.summaries'
    class: 'Bundle'

inference:
    output_dir: '/global/homes/t/tsfraser/voids_sunbird/sunbird/scripts/inference/chains/'

priors:
    stats_module: 'scipy.stats'
    omega_b:
        distribution: 'uniform'
        min: 0.0220
        max: 0.0229

    omega_cdm:
        distribution: 'uniform'
        min: 0.1032
        max: 0.140

    sigma8_m:
        distribution: 'uniform'
        min: 0.678
        max: 0.938
    n_s:
        distribution: 'uniform'
        min: 0.9012
        max: 1.025
    nrun:
        distribution: 'uniform'
        min: -0.038
        max: 0.038

    N_ur:
        distribution: 'uniform'
        min: 1.188
        max: 2.889

    w0_fld:
        distribution: 'uniform'
        min: -1.22
        max: -0.726

    wa_fld:
        distribution: 'uniform'
        min: -0.628
        max: 0.621


    logM1:
        distribution: 'uniform'
        min: 13
        max: 16

    logM_cut:
        distribution: 'uniform'
        min: 12.
        max: 14.5

    alpha:
        distribution: 'uniform'
        min: 0.4
        max: 1.5

    sigma:
        distribution: 'uniform'
        min: 0.05
        max: 0.9

    kappa:
        distribution: 'uniform'
        min: 0.05
        max: 1.25

