slice_filters:
    s: [0.7,120.]

select_filters:
    multipoles: [0,1]

statistics: ['voids']
data:
    observation: 
        class: 'CMASS'
        args:
            galactic_cap: 'ngc'
    covariance:
        class: 'Patchy'
        add_emulator_error: false
        add_simulation_error: false
        volume_scaling: 1.0

fixed_parameters: ['nrun','N_ur','w0_fld','wa_fld'] 

theory_model:
    module: 'sunbird.summaries'
    class: 'Bundle'

inference:
    output_dir: '/pscratch/sd/e/epaillas/voids_sunbird/scripts/inference/chains/'

priors:
    stats_module: 'scipy.stats'
    omega_b:
        distribution: 'norm'
        mean: 0.02268
        dispersion: 0.00038

    omega_cdm:
        distribution: 'uniform'
        min: 0.1032
        max: 0.140

    sigma8_m:
        distribution: 'uniform'
        min: 0.678
        max: 0.938
    n_s:
        distribution: 'uniform'
        min: 0.9012
        max: 1.025
    nrun:
        distribution: 'uniform'
        min: -0.038
        max: 0.038

    N_ur:
        distribution: 'uniform'
        min: 1.188
        max: 2.889

    w0_fld:
        distribution: 'uniform'
        min: -1.22
        max: -0.726

    wa_fld:
        distribution: 'uniform'
        min: -0.628
        max: 0.621

